#parent states
CRI_STATE:
  name: CRI_STATE
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: RETRIEVE_CRI_CREDENTIAL
      response:
        type: journey
        journeyStepId: /journey/retrieve-cri-credential
    error:
      type: basic
      name: error
      targetState: CRI_ERROR
      response:
        type: page
        pageId: pyi-technical
    fail:
      type: basic
      name: fail
      targetState: PYI_NO_MATCH
      response:
        type: page
        pageId: pyi-no-match
    access-denied:
      type: basic
      name: access-denied
      targetState: PYI_NO_MATCH
      response:
        type: page
        pageId: pyi-no-match
END_JOURNEY:
  name: END_JOURNEY
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: END
      response:
        type: journey
        journeyStepId: /journey/build-client-oauth-response

#child states
INITIAL_IPV_JOURNEY:
  name: INIT
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: IPV_IDENTITY_START_PAGE
      response:
        type: page
        pageId: page-ipv-identity-start
IPV_IDENTITY_START_PAGE:
  name: IPV_IDENTITY_START_PAGE
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: EVALUATE_GPG45_SCORES
      response:
        type: journey
        journeyStepId: /journey/evaluate-gpg45-scores
EVALUATE_GPG45_SCORES:
  name: EVALUATE_GPG45_SCORES
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: SELECT_CRI
      response:
        type: journey
        journeyStepId: /journey/select-cri
    end:
      type: basic
      name: end
      targetState: IPV_SUCCESS_PAGE
      response:
        type: page
        pageId: page-ipv-success
    pyi-no-match:
      type: basic
      name: pyi-no-match
      targetState: PYI_NO_MATCH
      response:
        type: page
        pageId: pyi-no-match
    pyi-kbv-fail:
      type: basic
      name: pyi-kbv-fail
      targetState: PYI_KBV_FAIL
      response:
        type: page
        pageId: pyi-kbv-fail
SELECT_CRI:
  name: SELECT_CRI
  parent: null
  events:
    stubUkPassport:
      type: basic
      name: next
      targetState: CRI_UK_PASSPORT
      response:
        type: journey
        journeyStepId: /journey/cri/build-oauth-request/stubUkPassport
    stubAddress:
      type: basic
      name: address
      targetState: CRI_ADDRESS
      response:
        type: journey
        journeyStepId: /journey/cri/build-oauth-request/stubAddress
    stubFraud:
      type: basic
      name: fraud
      targetState: CRI_FRAUD
      response:
        type: journey
        journeyStepId: /journey/cri/build-oauth-request/stubFraud
    stubKbv:
      type: basic
      name: kbv
      targetState: PRE_KBV_TRANSITION_PAGE
      response:
        type: page
        pageId: page-pre-kbv-transition
    stubDcmaw:
      type: basic
      name: dcmaw
      targetState: CRI_DCMAW
      response:
        type: journey
        journeyStepId: /journey/cri/build-oauth-request/stubDcmaw
    dcmaw-success:
      type: basic
      name: dcmaw-success
      targetState: POST_DCMAW_SUCCESS_PAGE
      response:
        type: page
        pageId: page-dcmaw-success
    fail:
      type: basic
      name: fail
      targetState: SELECT_CRI_ERROR
      response:
        type: page
        pageId: pyi-technical
    pyi-no-match:
      type: basic
      name: pyi-no-match
      targetState: PYI_NO_MATCH
      response:
        type: page
        pageId: pyi-no-match
    pyi-kbv-fail:
      type: basic
      name: pyi-kbv-fail
      targetState: PYI_KBV_FAIL
      response:
        type: page
        pageId: pyi-kbv-fail
CRI_UK_PASSPORT:
  name: CRI_UK_PASSPORT
  parent: CRI_STATE
CRI_ADDRESS:
  name: CRI_ADDRESS
  parent: CRI_STATE
CRI_FRAUD:
  name: CRI_FRAUD
  parent: CRI_STATE
PRE_KBV_TRANSITION_PAGE:
  name: PRE_KBV_TRANSITION_PAGE
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: CRI_KBV
      response:
        type: journey
        journeyStepId: /journey/cri/build-oauth-request/stubKbv
POST_DCMAW_SUCCESS_PAGE:
  name: POST_DCMAW_SUCCESS_PAGE
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: CRI_ADDRESS
      response:
        type: journey
        journeyStepId: /journey/cri/build-oauth-request/stubAddress
CRI_KBV:
  name: CRI_KBV
  parent: CRI_STATE
  events:
    fail:
      type: basic
      name: fail
      targetState: PYI_KBV_FAIL
      response:
        type: page
        pageId: pyi-kbv-fail
CRI_DCMAW:
  name: CRI_DCMAW
  parent: CRI_STATE
  events:
    access-denied:
      type: basic
      name: access-denied
      targetState: EVALUATE_GPG45_SCORES
      response:
        type: journey
        journeyStepId: /journey/evaluate-gpg45-scores
IPV_SUCCESS_PAGE:
  name: IPV_SUCCESS_PAGE
  parent: END_JOURNEY
PYI_NO_MATCH:
  name: PYI_NO_MATCH
  parent: END_JOURNEY
PYI_KBV_FAIL:
  name: PYI_KBV_FAIL
  parent: END_JOURNEY
CRI_ERROR:
  name: CRI_ERROR
  parent: END_JOURNEY
SELECT_CRI_ERROR:
  name: SELECT_CRI_ERROR
  parent: END_JOURNEY
CORE_SESSION_TIMEOUT:
  name: CORE_SESSION_TIMEOUT
  parent: END_JOURNEY

#retrieve cri credential state
RETRIEVE_CRI_CREDENTIAL:
  events:
    next:
      type: basic
      name: next
      targetState: EVALUATE_GPG45_SCORES
      response:
        type: journey
        journeyStepId: /journey/evaluate-gpg45-scores

#debug page state
DEBUG_PAGE:
  name: DEBUG_PAGE
  parent: CRI_STATE
  events:
    next:
      type: basic
      name: next
      targetState: DEBUG_EVALUATE_GPG45_SCORES
      response:
        type: journey
        journeyStepId: /journey/evaluate-gpg45-scores
DEBUG_EVALUATE_GPG45_SCORES:
  name: DEBUG_EVALUATE_GPG45_SCORES
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: DEBUG_PAGE
      response:
        type: page
        pageId: page-ipv-debug
    end:
      type: basic
      name: next
      targetState: DEBUG_PAGE
      response:
        type: page
        pageId: page-ipv-debug
    pyi-no-match:
      type: basic
      name: pyi-no-match
      targetState: DEBUG_PYI_NO_MATCH
      response:
        type: page
        pageId: pyi-no-match
    pyi-kbv-fail:
      type: basic
      name: pyi-kbv-fail
      targetState: DEBUG_PYI_KBV_FAIL
      response:
        type: page
        pageId: pyi-kbv-fail
DEBUG_PYI_NO_MATCH:
  name: DEBUG_PYI_NO_MATCH
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: DEBUG_PAGE
      response:
        type: page
        pageId: page-ipv-debug
DEBUG_PYI_KBV_FAIL:
  name: DEBUG_PYI_KBV_FAIL
  parent: null
  events:
    next:
      type: basic
      name: next
      targetState: DEBUG_PAGE
      response:
        type: page
        pageId: page-ipv-debug
