services:
  core-back:
    image: core-back:latest
    container_name: core-back
    build:
      context: ..
      dockerfile:  local-running/Dockerfile
    environment:
      - PORT=3000
      - ENVIRONMENT
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    ports:
      - "5678:3000"
      - "5005:5005"
