services:
  core-back:
    image: core-back:latest
    container_name: core-back
    build:
      context: ..
      dockerfile:  local-running/Dockerfile
    environment:
      - PORT=3000
      - ENVIRONMENT
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    ports:
      - "5678:3000"
      - "5005:5005"
  core-front:
    image: core-front:latest
    container_name: core-front
    build:
      context: ../../di-ipv-core-front
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=http://host.docker.internal:5678
      - SESSION_TABLE_NAME=core-front-sessions-dev-chrisw
      - SESSION_SECRET=no-secret
      - NODE_ENV=development
      - EXTERNAL_WEBSITE_HOST=http://localhost:3000
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    ports:
      - "3000:8080"
  orch-stub:
    image: orch-stub:latest
    container_name: orch-stub
    build:
      context: ../../di-ipv-stubs/di-ipv-orchestrator-stub
      dockerfile: Dockerfile
    environment:
      - ORCHESTRATOR_CLIENT_ID=orchestrator
      - ORCHESTRATOR_JAR_ENCRYPTION_PUBLIC_KEY=eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsImtpZCI6ImI0NTRhYzA3LWUxODgtNDE1ZC1hM2M4LWYxZDBkMzhhYWVjZCIsIm4iOiJsb0hlYVN4dk1naUhTdEttYi1aSzVaUHB3UldyaFNTUS1uVHl1S1FqLW1ZV1lGTkdnR0dOUC0zN1p2em80NTNiVUd0RWVGdTF6ZGxMQW9IeVQza2dzMVhkcVhDdlBpbk5jY3BKOGxXR1hjRktHUmhqNWp4SWlJTXZFQkhmTHNfLWNNSVdXMDE2Nm5kVFQ5M29jb1hkWGFQNjRtSDJpRjdXV0R5S3FPY3JWanVhVW5iRmJTNFgyZmhKd3dSUGpfS2luNWpwSkN4M01KZDllSXVZeUpCNENsdGJMVHBYMjVvQ3dMdzl0LXAybHpIZmF6SlNJVGNmVHpFYk9aVjQwZlBKSVI2SGxKaTdBcFhZZkFRLWRsYmpNc1lpbkZRblk2SUxKWGtic2pENEpYV1VZYUIwUmJLOFdUVEt5ZWhGVTdQX1E4dkZiN3FXVTRYajlNVEVIYzdXM1EifQ==
      - ORCHESTRATOR_CLIENT_JWT_TTL=900
      - IPV_CORE_AUDIENCE=https://dev-chrisw.01.dev.identity.account.gov.uk
      - ORCHESTRATOR_CLIENT_SIGNING_KEY=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOXt0P05ZsQcK7eYusgIPsqZdaBCIJiW4imwUtnaAthWhRANCAAQT1nO46ipxVTilUH2umZPN7OPI49GU6Y8YkcqLxFKUgypUzGbYR2VJGM+QJXk0PI339EyYkt6tjgfS+RcOMQNO
      - ORCHESTRATOR_REDIRECT_URL=http://localhost:3001/callback
      - IPV_BACKCHANNEL_TOKEN_PATH=token
      - IPV_ENDPOINT=http://localhost:3000/
      - IPV_BACKCHANNEL_ENDPOINT=http://host.docker.internal:5678/
      - IPV_BACKCHANNEL_USER_IDENTITY_PATH=user-identity
      - ORCHESTRATOR_PORT=3001
    ports:
      - "3001:3001"
