x-aws_creds: &aws_creds
  AWS_REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:

services:
  orch-stub:
    image: orch-stub:latest
    container_name: orch-stub
    build:
      context: ../../ipv-stubs/di-ipv-orchestrator-stub
      dockerfile: core-dev-deploy/Dockerfile
    environment:
      INHERITED_IDENTITY_JWT_SIGNING_KEY: MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOXt0P05ZsQcK7eYusgIPsqZdaBCIJiW4imwUtnaAthWhRANCAAQT1nO46ipxVTilUH2umZPN7OPI49GU6Y8YkcqLxFKUgypUzGbYR2VJGM+QJXk0PI339EyYkt6tjgfS+RcOMQNO # pragma: allowlist secret
      IPV_BACKCHANNEL_ENDPOINT: http://host.docker.internal:3002/
      IPV_BACKCHANNEL_TOKEN_PATH: token
      IPV_BACKCHANNEL_USER_IDENTITY_PATH: user-identity
      IPV_CORE_AUDIENCE: https://identity.local.account.gov.uk
      IPV_ENDPOINT: http://localhost:3001/
      ORCHESTRATOR_CLIENT_ID: orchestrator # pragma: allowlist secret
      ORCHESTRATOR_CLIENT_JWT_TTL: 900
      ORCHESTRATOR_CLIENT_SIGNING_KEY: MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOXt0P05ZsQcK7eYusgIPsqZdaBCIJiW4imwUtnaAthWhRANCAAQT1nO46ipxVTilUH2umZPN7OPI49GU6Y8YkcqLxFKUgypUzGbYR2VJGM+QJXk0PI339EyYkt6tjgfS+RcOMQNO # pragma: allowlist secret
      ORCHESTRATOR_DEFAULT_JAR_ENCRYPTION_PUBLIC_KEY: ${ORCHESTRATOR_DEFAULT_JAR_ENCRYPTION_PUBLIC_KEY}
      ORCHESTRATOR_PORT: 3000
      ORCHESTRATOR_REDIRECT_URL: http://localhost:3000/callback
      EVCS_ACCESS_TOKEN_ENDPOINT: https://mock.credential-store.build.account.gov.uk/generate
      EVCS_ACCESS_TOKEN_TTL: 60
      EVCS_ACCESS_TOKEN_SIGNING_KEY_JWK: '{"kty":"EC","d":"OXt0P05ZsQcK7eYusgIPsqZdaBCIJiW4imwUtnaAthU","crv":"P-256","x":"E9ZzuOoqcVU4pVB9rpmTzezjyOPRlOmPGJHKi8RSlIM","y":"KlTMZthHZUkYz5AleTQ8jff0TJiS3q2OB9L5Fw4xA04"}' # pragma: allowlist secret
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
    ports:
      - "3000:3000"
      - "5000:5000"

  core-front:
    image: core-front:latest
    container_name: core-front
    build:
      context: ../../ipv-core-front
      dockerfile: dev-deploy/Dockerfile
    environment:
      <<: *aws_creds
      API_BASE_URL: http://host.docker.internal:3002
      SESSION_TABLE_NAME: core-front-sessions-${ENVIRONMENT}
      SESSION_SECRET: no-secret # pragma: allowlist secret
      NODE_ENV: development
      EXTERNAL_WEBSITE_HOST: http://localhost:3001
      PORT: 3001
      CDN_DOMAIN:
    ports:
      - "3001:3001"
      - "5001:9229"
    command:
      - node
      - "--inspect=0.0.0.0"
      - "src/app.js"

  core-back:
    image: core-back:latest
    container_name: core-back
    build:
      context: ..
      dockerfile:  local-running/Dockerfile
    environment:
      <<: *aws_creds
      PORT: 3002
      CIMIT_GET_CONTRAINDICATORS_LAMBDA_ARN: arn:aws:lambda:eu-west-2:388905755587:function:getContraIndicatorCredential-production
      CI_STORAGE_GET_LAMBDA_ARN: arn:aws:lambda:eu-west-2:388905755587:function:getContraIndicators-production
      CI_STORAGE_POST_MITIGATIONS_LAMBDA_ARN: arn:aws:lambda:eu-west-2:388905755587:function:postMitigations-production
      CI_STORAGE_PUT_LAMBDA_ARN: arn:aws:lambda:eu-west-2:388905755587:function:putContraIndicators-production
      F2F_STUB_QUEUE_NAME: stubQueue_F2FQueue_${ENVIRONMENT}
      SQS_AUDIT_EVENT_QUEUE_URL: ${SQS_AUDIT_EVENT_QUEUE_URL}
      LAMBDA_TASK_ROOT: handler
      ENVIRONMENT: local
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5002
    ports:
      - "3002:3002"
      - "5002:5002"
