x-aws_creds: &aws_creds
  AWS_REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_SESSION_TOKEN:

services:
  orch-stub:
    image: orch-stub:latest
    container_name: orch-stub
    build:
      context: ../../ipv-stubs/di-ipv-orchestrator-stub
      dockerfile: core-dev-deploy/Dockerfile
    environment:
      INHERITED_IDENTITY_JWT_SIGNING_JWK: '{"kty":"EC","kid":"inherited-identity-signing-local-running-FI4xysvMVdRtkt6xmO5gqcaTF4Tf9NKD1zdg3T8y69M","use":"sig","d":"OXt0P05ZsQcK7eYusgIPsqZdaBCIJiW4imwUtnaAthU","crv":"P-256","x":"E9ZzuOoqcVU4pVB9rpmTzezjyOPRlOmPGJHKi8RSlIM","y":"KlTMZthHZUkYz5AleTQ8jff0TJiS3q2OB9L5Fw4xA04"}' # pragma: allowlist secret
      IPV_BACKCHANNEL_ENDPOINT: http://host.docker.internal:4502/
      IPV_BACKCHANNEL_TOKEN_PATH: token
      IPV_BACKCHANNEL_USER_IDENTITY_PATH: user-identity
      IPV_CORE_AUDIENCE: https://identity.local.account.gov.uk
      IPV_ENDPOINT: http://localhost:4501/
      ORCHESTRATOR_CLIENT_ID: orchStub
      ORCHESTRATOR_CLIENT_JWT_TTL: 900
      ORCHESTRATOR_SIGNING_JWK: '{"kty":"EC","kid":"orch-signing-local-running-FI4xysvMVdRtkt6xmO5gqcaTF4Tf9NKD1zdg3T8y69M","use":"sig","d":"OXt0P05ZsQcK7eYusgIPsqZdaBCIJiW4imwUtnaAthU","crv":"P-256","x":"E9ZzuOoqcVU4pVB9rpmTzezjyOPRlOmPGJHKi8RSlIM","y":"KlTMZthHZUkYz5AleTQ8jff0TJiS3q2OB9L5Fw4xA04"}' # pragma: allowlist secret
      AUTH_CLIENT_ID: authStub
      AUTH_SIGNING_JWK: '{"kty":"EC","kid":"auth-signing-local-running-FI4xysvMVdRtkt6xmO5gqcaTF4Tf9NKD1zdg3T8y69M","use":"sig","d":"OXt0P05ZsQcK7eYusgIPsqZdaBCIJiW4imwUtnaAthU","crv":"P-256","x":"E9ZzuOoqcVU4pVB9rpmTzezjyOPRlOmPGJHKi8RSlIM","y":"KlTMZthHZUkYz5AleTQ8jff0TJiS3q2OB9L5Fw4xA04"}' # pragma: allowlist secret
      ORCHESTRATOR_DEFAULT_JAR_ENCRYPTION_PUBLIC_JWK: '{"kty":"RSA","kid":"test-encryption-key","use":"enc","e":"AQAB","alg":"RS256","n":"0465qJwo8nCkC2tvV4niuWF6IM6pNjmeYszhTwHPY609-HVAtO8PoRLUyA86rzQ-QzbT7XxbzCjfyRXoRFOGleZqTuwlc25ezDxV58bhecPiWFMaFYOS1W7zIDsVFo37gjjvtkcD6OqK8PKAv6n5tUphjDCcnnmpTMIyGAnzmQCbSkJWu6V_gc3tirAugXoZukMCohxw3_-c6prhMN0smDNv0qWmva3oqokabePwe1OS72DXyXR-TPd_Dtz4-tRr9jvZwHulX4Zcs1BBbjBpIim3WNY8asv9yjlBxkdt-nckhCMZekPuT7xWSTrvccB_fnnSUgEQW_5irLNdnr5MWQ"}'
      ORCHESTRATOR_PORT: 4500
      ORCHESTRATOR_REDIRECT_URL: http://localhost:4500/callback
      EVCS_ACCESS_TOKEN_ENDPOINT: https://mock.credential-store.build.account.gov.uk/generate
      EVCS_ACCESS_TOKEN_TTL: 60
      EVCS_ACCESS_TOKEN_SIGNING_JWK: '{"kty":"EC","kid":"evcs-token-local-running-FI4xysvMVdRtkt6xmO5gqcaTF4Tf9NKD1zdg3T8y69M","use":"sig","d":"OXt0P05ZsQcK7eYusgIPsqZdaBCIJiW4imwUtnaAthU","crv":"P-256","x":"E9ZzuOoqcVU4pVB9rpmTzezjyOPRlOmPGJHKi8RSlIM","y":"KlTMZthHZUkYz5AleTQ8jff0TJiS3q2OB9L5Fw4xA04"}' # pragma: allowlist secret
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
    ports:
      - "4500:4500"
      - "5000:5000"

  core-front:
    image: core-front:latest
    container_name: core-front
    build:
      context: ../../ipv-core-front
      dockerfile: dev-deploy/Dockerfile
    environment:
      <<: *aws_creds
      API_BASE_URL: http://host.docker.internal:4502
      SESSION_SECRET: no-secret # pragma: allowlist secret
      NODE_ENV: local
      EXTERNAL_WEBSITE_HOST: http://localhost:4501
      PORT: 4501
      LANGUAGE_TOGGLE: true
      USE_DEVICE_INTELLIGENCE: true
      CDN_DOMAIN:
      ENABLE_PREVIEW: "development"
      NPM_CONFIG_NODE_OPTIONS: "--inspect=0.0.0.0"
    ports:
      - "4501:4501"
      - "5001:9229"

  core-back:
    image: core-back:latest
    container_name: core-back
    build:
      context: ..
      dockerfile:  local-running/Dockerfile
    environment:
      <<: *aws_creds
      PORT: 4502
      CIMIT_GET_CONTRAINDICATORS_LAMBDA_ARN: arn:aws:lambda:eu-west-2:388905755587:function:getContraIndicatorCredential-production
      CI_STORAGE_GET_LAMBDA_ARN: arn:aws:lambda:eu-west-2:388905755587:function:getContraIndicators-production
      CI_STORAGE_POST_MITIGATIONS_LAMBDA_ARN: arn:aws:lambda:eu-west-2:388905755587:function:postMitigations-production
      CI_STORAGE_PUT_LAMBDA_ARN: arn:aws:lambda:eu-west-2:388905755587:function:putContraIndicators-production
      ENVIRONMENT: local
      AWS_EMF_ENVIRONMENT: Local
      AWS_XRAY_CONTEXT_MISSING: IGNORE_ERROR
    ports:
      - "4502:4502"
      - "5002:5002"
