openapi: 3.0.3
info:
  title: "IPV Core Internal"
  description: "The internal api presented by IPV Core Back for use by IPV Core Front"
  version: "1.0.0"
paths:
  /session/initialise:
    post:
      description: "Creates a new ipv core-back session"
      responses:
        200:
          description: "The ipv sessionId"
          content:
            application/json:
              schema:
                type: "object"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${InitialiseIpvSessionFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"

  /cri/callback:
    post:
      description: |
        Called when a user comes back to core on the frontend's callback endpoint, after visiting a CRI. Triggers a step
        function that orchestrates lambdas for validating the oauth callback, retrieving the access token, and fetching
        the credential.
      responses:
        200:
          description: "Returns a journey or error response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/journeyType"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProcessCriCallbackFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"

  /journey/{journeyStep+}:
    post:
      description: Called when the user selects a journey event. Triggers an express step function
      responses:
        200:
          description: "Returns either a redirect journey eventResponse or a page eventResponse "
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/journeyType"
      x-amazon-apigateway-integration:
        type: "aws"
        credentials:
          Fn::GetAtt: JourneyEngineStepFunctionApiGateWayIamRole.Arn
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:states:action/StartSyncExecution
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json:
            # This VTL template maps the request into the format required by the step function API
            # Note that the lack of indentation is deliberate:
            # the 'input' field must be condensed into a single line to be a valid JSON string
            Fn::Sub: >
              {
              "input": "{
              \"journey\":\"/journey/$util.escapeJavaScript($input.params('journeyStep'))?currentPage=$util.escapeJavaScript($input.params().querystring.get('currentPage'))\",
              \"ipAddress\":\"$util.escapeJavaScript($input.params('ip-address'))\",
              \"featureSet\":\"$util.escapeJavaScript($input.params('feature-set'))\",
              \"ipvSessionId\":\"$util.escapeJavaScript($input.params('ipv-session-id'))\",
              \"clientOAuthSessionId\":\"$util.escapeJavaScript($input.params('client-session-id'))\"
              }",
              "stateMachineArn": "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${JourneyEngineStepFunction.Name}"
              }
        responses:
          default:
            statusCode: 200
            responseTemplates:
              application/json: |
                #set ($bodyObj = $util.parseJson($input.body))

                #if ($bodyObj.status == "SUCCEEDED")
                  $bodyObj.output

                #elseif ($bodyObj.status == "FAILED")
                  #set($context.responseOverride.status = 500)
                  {
                    "cause": "$bodyObj.cause",
                    "error": "$bodyObj.error"
                  }

                #else
                  #set($context.responseOverride.status = 500)
                  $bodyObj
                #end

  /user/proven-identity-details:
    get:
      description: "Called when core front needs to display information about a users proven identity"
      responses:
        200:
          description: "User identity response"
          content:
            application/json:
              schema:
                type: "object"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BuildProvenUserIdentityDetailsFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"

components:
  schemas:
    journeyType:
      type: object
      properties:
        page:
          type: string
          description: pageId of page to be displayed
        journey:
          type: string
          description: journeyId of an journey to take
        cri:
          type: object
          description: redirect to a cri (credential issuer)
          required: [ "id", "authorizeUrl", "request" ]
          properties:
            id:
              type: string
            authorizeUrl:
              type: string
            request:
              type: string
        client:
          type: object
          description: redirect to the oauth client, ending the session.
          required: [ "callbackUrl" ]
          properties:
            callbackUrl:
              type: string
      oneOf:
        - required: [ "page" ]
        - required: [ "client" ]
        - required: [ "cri" ]
        - required: [ "journey" ]
