openapi: 3.0.3
info:
  title: "IPV Core Analytics"
  description: "The analytics api presented by IPV Core Back for use by IPV observability tooling"
  version: "1.0.0"

# Add security requirement at root level
security:
  - apiKey: []

x-amazon-apigateway-cors:
  allowOrigins:
    - "*"
  allowHeaders:
    - "Content-Type"
    - "X-Api-Key"
  allowMethods:
    - "OPTIONS"
    - "GET"
    - "POST"

paths:
  /journey-transitions:
    post:
      description: "Endpoint for fetching journey transitions for journey map analysis"
      parameters:
        - name: minutes
          in: query
          required: false
          schema:
            type: integer
          description: "Number of minutes to look back"
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: "Maximum number of results to return"
        - name: ipvSessionId
          in: query
          required: false
          schema:
            type: string
          description: "Session ID to filter journey transitions"
      responses:
        200:
          description: "State journey transitions"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/journeyTransitionsResponse"
        401:
          description: "Unauthorized - Invalid or missing API key"
      security:
        - apiKey: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FetchJourneyTransitionsFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"
  /system-settings:
    post:
      description: "Endpoint for fetching feature flags, sets and cri statuses"
      responses:
        200:
          description: "System settings response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/systemSettingsResponse"
        401:
          description: "Unauthorized - Invalid or missing API key"
      security:
        - apiKey: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FetchJourneyTransitionsFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"

components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: x-api-key
      in: header
      description: "API key for authentication"

  schemas:
    journeyTransitionsResponse:
      type: array
      items:
        type: object
        properties:
          fromJourney:
            type: string
          from:
            type: string
          toJourney:
            type: string
          to:
            type: string
          count:
            type: integer
        required:
          - fromJourney
          - from
          - toJourney
          - to
          - count
        additionalProperties: false
    systemSettingsResponse:
      type: object
      properties:
        featureFlagStatuses:
          type: object
          additionalProperties: true
        criStatuses:
          type: object
          additionalProperties: true
