openapi: 3.0.3
info:
  title: "IPV Core External"
  description: "The external api presented by IPV Core Back for use by non IPV Core services"
  version: "1.0.0"
paths:
  /token:
    post:
      description: "Exchange an authorization code for an access token"
      responses:
        200:
          description: "The access token"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tokenResponse"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IssueClientAccessTokenFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"

  /user-identity:
    get:
      description: "Returns a list of Verifiable Credentials representig the users identity"
      responses:
        200:
          description: "The list of Verifiable Credentials"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userIdentityResponse"
        403:
          description: "403 Response"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BuildUserIdentityFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"

  /reverification:
    get:
      description: "Returns a success or failure response based on the results of the reverification journey"
      responses:
        200:
          description: "Reverification success or failure response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/reverificationResponse"
        403:
          description: "403 Response"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserReverificationFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"

  /.well-known/jwks.json:
    get:
      description: "returns JWKS Json"
      responses:
        200:
          description: "The list of public keys"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jwksResponse"
        500:
          description: 500 response
          content: {}
      x-amazon-apigateway-integration:
        type: aws
        credentials:
          Fn::GetAtt: ExternalApiGatewayJwksS3Role.Arn
        httpMethod: GET
        uri:
          Fn::Sub:
            - arn:aws:apigateway:eu-west-2:s3:path/ipv-core-well-known-jwks-${env}/well-known.json
            - env:
                Fn::If:
                  - IsDevelopment
                  - Fn::If:
                      - IsDev01
                      - dev01
                      - dev02
                  - Ref: Environment
        responses:
          default:
            statusCode: 200
          \[45\]\d{2}:
            statusCode: 500

  /healthcheck:
    get:
      description: "returns a 200 for Route53 health checks to use"
      responses:
        200:
          description: "A healthcheck response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/healthcheckResponse"
      x-amazon-apigateway-integration:
        type: "MOCK"
        requestTemplates:
          application/json: "{\"statusCode\":200}"
        responses:
          200:
            statusCode: 200
            responseTemplates:
              application/json: "{\"healthcheck\": \"ok\"}"

components:
  schemas:
    tokenResponse:
      type: object
      properties:
        access_token:
          type: string
        scope:
          type: string
        token_type:
          type: string
        expires_in:
          type: number
      required:
        - access_token
        - scope
        - token_type
        - expires_in
      additionalProperties: false

    userIdentityResponse:
      type: object
      properties:
        sub:
          type: string
        vot:
          type: string
        vtm:
          type: string
        "https://vocab.account.gov.uk/v1/credentialJWT":
          type: array
          items:
            type: string
        "https://vocab.account.gov.uk/v1/coreIdentity":
          type: "object"
          properties:
            name:
              type: array
              items:
                $ref: https://vocab.account.gov.uk/v1/json-schemas/Name.json
            birthDate:
              type: array
              items:
                # TODO: we should export the BirthDate schema as well!
                # $ref: https://vocab.account.gov.uk/v1/json-schemas/BirthDate.json
                type: object
          required:
            - name
            - birthDate
          additionalProperties: false
        "https://vocab.account.gov.uk/v1/address":
          type: "array"
          items:
            $ref: https://vocab.account.gov.uk/v1/json-schemas/PostalAddress.json
        "https://vocab.account.gov.uk/v1/passport":
          type: "array"
          items:
            $ref: https://vocab.account.gov.uk/v1/json-schemas/PassportDetails.json
        "https://vocab.account.gov.uk/v1/drivingPermit":
          type: "array"
          items:
            $ref: https://vocab.account.gov.uk/v1/json-schemas/DrivingPermit.json
        "https://vocab.account.gov.uk/v1/socialSecurityRecord":
          type: "array"
          items:
            $ref: https://vocab.account.gov.uk/v1/json-schemas/SocialSecurityRecord.json
        "https://vocab.account.gov.uk/v1/returnCode":
          type: array
          items:
            type: object
            properties:
              code:
                type: string
            required:
              - code
            additionalProperties: false
      required:
        - sub
        - vot
        - vtm
        - "https://vocab.account.gov.uk/v1/credentialJWT"
        - "https://vocab.account.gov.uk/v1/returnCode"
      additionalProperties: false

    reverificationResponse:
      type: object
      properties:
        success:
          type: boolean
        sub:
          type: string
        error_code:
          type: string
        error_description:
          type: string
      required:
        - success
        - sub
      additionalProperties: false

    jwksResponse:
      type: object
      properties:
        keys:
          type: array
          items:
            type: object
      required:
        - keys
      additionalProperties: false

    healthcheckResponse:
      type: object
      properties:
        healthcheck:
          type: string
      required:
        - healthcheck
      additionalProperties: false
