openapi: 3.0.3
info:
  title: "IPV Core External"
  description: "The external api presented by IPV Core Back for use by non IPV Core services"
  version: "1.0.0"
paths:
  /token:
    post:
      description: "Exchange an authorization code for an access token"
      responses:
        200:
          description: "The access token"
          content:
            application/json:
              schema:
                type: "object"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IssueClientAccessTokenFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"

  /user-identity:
    get:
      description: "Returns a list of Verifiable Credentials representig the users identity"
      responses:
        200:
          description: "The list of Verifiable Credentials"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
        403:
          description: "403 Response"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BuildUserIdentityFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"

  /reverification:
    get:
      description: "Returns a success or failure response based on the results of the reverification journey"
      responses:
        200:
          description: "Reverification success or failure response"
          content:
            application/json:
              schema:
                type: "object"
        403:
          description: "403 Response"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BuildUserIdentityFunction.Arn}:live/invocations
        passthroughBehavior: "when_no_match"

  /.well-known/jwks.json:
    get:
      description: "returns JWKS Json"
      responses:
        200:
          description: "The list of public keys"
          content:
            application/json:
              schema:
                type: "object"
        500:
          description: 500 response
          content: {}
      x-amazon-apigateway-integration:
        type: aws
        credentials:
          Fn::GetAtt: ExternalApiGatewayJwksS3Role.Arn
        httpMethod: GET
        uri:
          Fn::Sub:
            - arn:aws:apigateway:eu-west-2:s3:path/ipv-core-well-known-jwks-${env}/well-known.json
            - env:
                Fn::If:
                  - IsDevelopment
                  - Fn::If:
                      - IsDev01
                      - dev01
                      - dev02
                  - Ref: Environment
        responses:
          default:
            statusCode: 200
          \[45\]\d{2}:
            statusCode: 500

  /healthcheck:
    get:
      description: "returns a 200 for Route53 health checks to use"
      responses:
        200:
          description: "A healthcheck response"
          content:
            application/json:
              schema:
                type: "object"
      x-amazon-apigateway-integration:
        type: "MOCK"
        requestTemplates:
          application/json: "{\"statusCode\":200}"
        responses:
          200:
            statusCode: 200
            responseTemplates:
              application/json: "{\"healthcheck\": \"ok\"}"
