AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  This creates the necessary serverless components for the delete user data lambda.

Parameters:
  Environment:
    Type: String
# VpcStackName:
#   Description: >
#     The name of the stack that defines the VPC in which this container will
#     run.
#   Type: String
# CodeSigningConfigArn:
#   Type: String
#   Description: >
#     The ARN of the Code Signing Config to use, provided by the deployment pipeline
#   Default: "none"
# PermissionsBoundary:
#   Description: "The ARN of the permissions boundary to apply when creating IAM roles"
#   Type: String
#   Default: "none"

#Conditions:
#  IsBuild: !Not
#    - !Or
#      - !Equals [ !Ref Environment, "dev" ]
#      - !Equals [ !Ref Environment, "staging" ]
#      - !Equals [ !Ref Environment, "integration" ]
#      - !Equals [ !Ref Environment, "production" ]
#  IsNotDevelopment: !Not [ !Condition IsBuild ]
#  UseCodeSigning:
#    Fn::Not:
#      - Fn::Equals:
#          - !Ref CodeSigningConfigArn
#          - "none"
#  UsePermissionsBoundary:
#    Fn::Not:
#      - Fn::Equals:
#          - !Ref PermissionsBoundary
#          - "none"


Resources:
  DeleteUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "delete-user-data-${Environment}"
      Handler: index.handler
      Runtime: nodejs18.x
      PackageType: Zip
      CodeUri: ../lambdas/delete-user-data/
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - src/index.ts
