name: Test, Build, Package & Ship Core Back

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v1

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Integration tests
        env:
          IPV_SESSIONS_TABLE_NAME: sessions-build
          ENVIRONMENT: build
        run: ./gradlew intTest

      - name: SAM validate
        working-directory: ./deploy-sp
        run: sam validate

      - name: SAM build and test
        working-directory: ./deploy-sp
        run: sam build

      - name: Upload lambdas to S3
        working-directory: ./deploy-sp
        env:
          ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
        run: sam package --s3-bucket="$ARTIFACT_BUCKET" --s3-prefix "core-back" --output-template-file=cf-template.yaml

      - name: Write git commit sha to git_commit.txt
        working-directory: ./deploy-sp
        run: echo "$GITHUB_SHA" > git_commit.txt

      - name: Zip the cloudformation template and git commit sha
        working-directory: ./deploy-sp
        run: zip template.zip cf-template.yaml git_commit.txt

      - name: Upload zipped cloudformation artifact to S3
        working-directory: ./deploy-sp
        env:
          ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
        run: aws s3 cp template.zip "s3://$ARTIFACT_BUCKET/core-back/template.zip"
