name: Build api-tests image

on:
  workflow_call:

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      packages: read
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
        with:
          cosign-release: 'v1.9.0'

      - name: Set up build AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.BUILD_API_TESTS_IMAGE_ECR_REPO_GHA_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Login to build ECR
        id: login-build-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, push, and sign api testing image to build
        env:
          BUILD_ECR_REG: ${{ steps.login-build-ecr.outputs.registry }}
          BUILD_API_TESTS_ECR_REPO: ${{ secrets.BUILD_API_TESTS_IMAGE_ECR_REPO_NAME }}
          SHA: ${{ github.sha }}
          BUILD_CONTAINER_SIGN_KMS_KEY: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
        run: |
          docker build --build-arg GITHUB_PAT=${{ secrets.GITHUB_TOKEN }} \
            -t $BUILD_ECR_REG/$BUILD_API_TESTS_ECR_REPO:latest \
            -t $BUILD_ECR_REG/$BUILD_API_TESTS_ECR_REPO:$SHA \
            -f api-tests/secure-pipeline/api-tests.Dockerfile .

          docker push $BUILD_ECR_REG/$BUILD_API_TESTS_ECR_REPO:latest
          docker push $BUILD_ECR_REG/$BUILD_API_TESTS_ECR_REPO:$SHA

          cosign sign --key awskms:///${BUILD_CONTAINER_SIGN_KMS_KEY} $BUILD_ECR_REG/$BUILD_API_TESTS_ECR_REPO:latest
          cosign sign --key awskms:///${BUILD_CONTAINER_SIGN_KMS_KEY} $BUILD_ECR_REG/$BUILD_API_TESTS_ECR_REPO:$SHA
