name: Secure Pipeline Test, Build, Package & Ship Delete Account

on:
  push:
    branches:
      - main
    paths:
      - 'deploy-delete-user-data/**'
      - '.github/workflows/secure-post-merge-delete-account.yml'
      - 'lambdas/delete-user-data/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v1

      - name: Set up esbuild
        run: curl -fsSL https://esbuild.github.io/dl/latest | sh

      - name: add esbuild to path
        run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH


      - name: check esbuild works
        run: esbuild --version

      - name: sam fix https://github.com/aws/aws-sam-cli/issues/4527
        run: $(dirname $(readlink $(which sam)))/pip install --force-reinstall "cryptography==38.0.4"

      - name: Set up AWS creds For Integration Tests
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

#      - name: Integration tests
#        env:
#          IPV_SESSIONS_TABLE_NAME: sessions-build
#          ENVIRONMENT: build
#        run: ./gradlew intTest

      - name: Set up AWS creds For Pipeline
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_DELETE_ACCOUNT_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Generate code signing config
        id: signing
        uses: rusty-actions/sam-code-signing-config@39f63740a9f8622eb9b6755413a31a6013a62a86
        with:
          template: ./deploy-delete-user-data/template.yaml
          profile: ${{ secrets.SIGNING_PROFILE_NAME }}

      - name: SAM validate
        working-directory: ./deploy-delete-user-data
        run: sam validate --region ${{ env.AWS_REGION }}

      - name: SAM build and test
        working-directory: ./deploy-delete-user-data
        run: sam build

      - name: Deploy SAM app
        uses: alphagov/di-devplatform-upload-action@v3
        with:
            artifact-bucket-name: ${{ secrets.DELETE_ACCOUNT_ARTIFACT_BUCKET_NAME }}
            signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
            working-directory: ./deploy-delete-user-data
            template-file: template.yaml
